# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Main dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '23:00'
      timezone: 'US/Mountain'
    groups:
      # Update all CDK dependencies together
      cdk:
        patterns:
          - 'aws-cdk*'
    ignore:
      # Ignore all Node types major updates to keep in sync with local version
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '23:00'
      timezone: 'US/Mountain'

  # Lambda functions
  - package-ecosystem: 'npm'
    directory: 'lib/lambda/c3-utils-layer/lib/nodejs'
    schedule:
      interval: 'daily'
      time: '23:00'
      timezone: 'US/Mountain'
  - package-ecosystem: 'npm'
    directory: 'lib/lambda/c3-create-payment-request'
    schedule:
      interval: 'daily'
      time: '23:00'
      timezone: 'US/Mountain'
  - package-ecosystem: 'npm'
    directory: 'lib/lambda/c3-tokenize-transaction'
    schedule:
      interval: 'daily'
      time: '23:00'
      timezone: 'US/Mountain'
  - package-ecosystem: 'npm'
    directory: 'lib/lambda/c3-submit-payment'
    schedule:
      interval: 'daily'
      time: '23:00'
      timezone: 'US/Mountain'
  - package-ecosystem: 'npm'
    directory: 'lib/lambda/c3-send-receipt'
    schedule:
      interval: 'daily'
      time: '23:00'
      timezone: 'US/Mountain'
  - package-ecosystem: 'npm'
    directory: 'lib/lambda/c3-subject-lookup'
    schedule:
      interval: 'daily'
      time: '23:00'
      timezone: 'US/Mountain'
  - package-ecosystem: 'npm'
    directory: 'lib/lambda/c3-send-agent-message'
    schedule:
      interval: 'daily'
      time: '23:00'
      timezone: 'US/Mountain'
  - package-ecosystem: 'npm'
    directory: 'lib/lambda/c3-validate-entry'
    schedule:
      interval: 'daily'
      time: '23:00'
      timezone: 'US/Mountain'
